language: java
jdk:
  - oraclejdk8
dist: trusty
node_js:
- '10'
services:
- mysql
cache:
  directories:
  - node_modules
before_install:
- pyenv global system 3.6
- pip3 install --user codecov
- nvm install 10.14.2
install:
- cd aa-gui && npm install && cd ..
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- mysql -e "create database IF NOT EXISTS aaserver; grant all on aaserver.* to 'root';SET
  GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;" -uroot
script:
- mvn test
- cd aa-gui && npm install && npm run webpack
after_success:
- codecov