language: java
jdk:
  - oraclejdk8
services:
  - mysql
  - redis-server
before_install:
  - pip install --user codecov
  - mysql -e "create database IF NOT EXISTS aaserver; grant all on aaserver.* to 'root';" -uroot
after_success:
  - codecov

