logging:
  config: classpath:logback.xml
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
#    org.hibernate.hql.internal.ast: ERROR
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.event: TRACE

server:
  contextPath: /aa/api
  server-header:
  session:
    timeout: 28800

scim_server_environment: test.surfconext
attribute_authorities_config_path: classpath:/attributeAuthorities.yml
authorization_access_token_url: http://localhost:8889/oauth/token
aggregate_cache_duration_milliseconds: 300000

orcid:
  authorization_uri: https://sandbox.orcid.org/oauth/authorize
  access_token_uri: https://sandbox.orcid.org/oauth/token
  client_id: APP-IP57TTCD5F8BAIGS
  client_secret: d3d8ddf6-9de9-49f7-9e18-9760cdebe208
  redirect_uri: http://localhost:8080/aa/api/redirect

security:
  internal_user_name: eb
  internal_password: secret

spring:
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/aaserver?autoReconnect=true&useSSL=false
    username: root
    password:
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  main:
    banner-mode: "off"

# We disable all endpoints except health for the load-balancer and info for git information.
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
