server:
  contextPath: /aa/api
  server-header:
  session:
    timeout: 28800

attribute_authorities_config_path: classpath:/attributeAuthorities.yml
authorization_access_token_url: https://authz.test2.surfconext.nl/oauth/token
aggregate_cache_duration_milliseconds: 300000

orcid:
  authorization_uri: https://sandbox.orcid.org/oauth/authorize
  access_token_uri: https://sandbox.orcid.org/oauth/token
  client_id:
  client_secret:
  redirect_uri: http://localhost:8080/aa/api/redirect

security:
  internal_user_name:
  internal_password:

pseudo:
  mail_postfix: surfconext.nl

spring:
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/aaserver?autoReconnect=true&useSSL=false
    username: root
    password:
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      remove-abandoned: true
  main:
    banner-mode: "off"

# In a multi master database setup toggle which machine is reponsible for cron jobs
cron_job_responsible: true
pseudo_emails_retention_days_period: 90


# We disable all endpoints except health for the load-balancer and info for git information.
endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
